version: "3.9"
services:
  backend:
    build:
      context: ./server      # 👈 backend folder
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: node server.js

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
