name: IntelliGrade CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (client)
        run: npm install
        working-directory: ./client

      - name: Run build
        run: CI=false npm run build
        working-directory: ./client

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build-and-test  # 👈 Waits for build to finish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  notify-render:
    name: Notify Render or Echo
    runs-on: ubuntu-latest
    needs: [sonarqube]
    steps:
      - name: Confirm Completion
        run: echo "SonarCloud check complete. Render will auto-deploy."
